### ISSUE TITLE
Cambiar los botones por links

### ISSUE THREAD

**Issue by ardiadrianadri** [GuillermoBaldan/ChuckNorris#2]
Utiliza los botones para realizar acciones que implican ejecuciones en JS. Si solo quieres navegar utiliza links

https://github.com/GuillermoBaldan/ChuckNorris/blob/eadb80f1ad7a98a2d55ad6713bb6bd35eb46b66c/index.html#L19

**Comment by GuillermoBaldan** [comment]
Vale, vale...yo solo quiero cosas SEOfriendly. Así que usaré link y le daré un estilo.
Muchas gracias!
