### ISSUE TITLE
Forms sin un submit

### ISSUE THREAD

**Issue by ardiadrianadri** [GuillermoBaldan/ChuckNorris#5]
En este formulario el action y el method no tienen sentido porque no dan ningún tipo de funcionalidad. 

https://github.com/GuillermoBaldan/ChuckNorris/blob/eadb80f1ad7a98a2d55ad6713bb6bd35eb46b66c/randomJokeByCategory.html#L12

**Comment by GuillermoBaldan** [comment]
Ok, I delete the attributes of 'action' and 'method'
